name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `pip show pyiec61850-ng` or git commit hash
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: api
    attributes:
      label: API layer
      options:
        - High-level (MMSClient / GooseSubscriber / etc.)
        - Low-level (raw pyiec61850 bindings)
        - Server API
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Module
      options:
        - MMS client
        - GOOSE subscriber/publisher
        - Sampled Values (SV)
        - TASE.2
        - Server
        - Build / wheel / compilation
        - Import / loading (.so/.pyd)
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Linux x86_64
        - Linux aarch64 / ARM
        - Windows x86_64
        - macOS x86_64
        - macOS ARM (Apple Silicon)
        - Docker
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal code to reproduce the issue
      render: python
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Python version, OS, how you installed the package
      placeholder: |
        - Python: 3.12.1
        - OS: Ubuntu 24.04
        - Install method: pip install pyiec61850-ng
        - libiec61850 version (if building from source): 1.5.3
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      description: Paste any error output, segfaults, or Wireshark captures
      render: text
    validations:
      required: false
