name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - MMS client
        - GOOSE subscriber/publisher
        - Sampled Values (SV)
        - TASE.2
        - Server API
        - New libiec61850 binding
        - High-level API wrapper
        - Build / packaging / wheels
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Why do you need this? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds?
    validations:
      required: false
